### ISSUE TITLE
How to create new omf flashable zip with custom font?

### ISSUE THREAD

**Issue by bishawjit-das** [khirendra03/Font-modules#5]

**Comment by khirendra03** [comment]
You can use [CFI](https://github.com/nongthaihoang/custom_font_installer) or omf template.
CFI is really easy to use.
Also if you use telegram then you can use our [bot](https://t.me/Magifonts_Support) to make yourself a custom font module

**Comment by bishawjit-das** [comment]
Thanks a lot, I am looking into that bot. Serves my purpose. Very useful.
