### ISSUE TITLE
Modules does not work with magisk 26.0

### ISSUE THREAD

**Issue by Subbuu316** [khirendra03/Font-modules#7]
New release of magisk breaks this modules does not allow the installation to be completed.

**Comment by khirendra03** [comment]
All the modules are tested on earlier version of magisk (i.e. version 25) and on Android 13. As for magisk 26 is just released, and I haven't seen what changes are there or tested on magisk 26.

Give us some time to test (and any changes to be made for magisk 26) on magisk 26.
